services:
  - type: web
    name: telegram-downloader-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: 8263130399:AAEAXbk90nTGreBxMVToaPNS2sp4ZIi-gnY
